name: Build Cython Wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, macos-13]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          pip install cython setuptools wheel build
      
      - name: Build wheel
        run: |
          python setup.py bdist_wheel
      
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl

  merge-artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Merge Wheels
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-wheels
          pattern: wheels-*